### ISSUE TITLE
iOS App crashes on Canvas.getContext()

### ISSUE THREAD

**Issue by Yaski** [wcandillon/react-native-webgpu#108]
I added react-native-webgpu to an existing project.
And I try to run simple HelloTriangle screen.
The app is crashing without message.
If I set breakpoint I get EXC_BAD_ACCESS error somewhere inside reanimated::ShareableHostFunction::ShareableHostFunction

By checking the lines of code I have found that the line 
`const context = ref.current!.getContext("webgpu")!; `
in HelloTriangle.tsx causes the crash

There are couple similar crashes mentioned on the reanimated repo, maybe they are somehow related
https://github.com/software-mansion/react-native-reanimated/issues/3884
https://github.com/software-mansion/react-native-reanimated/issues/3670

I use these versions of libraries:
```
"react-native": "0.75.2"
"react": "18.3.1"
"react-native-reanimated": "^3.15.0"
"react-native-wgpu": "^0.1.5"
```
Hermes is enabled and I disabled the new architecture (it wasn't working with react-native-webgpu on other project)

**Comment by Yaski** [comment]
I change reanimated version to:
`"react-native-reanimated": "~3.10.1"`
And there is the same crash

**Comment by wcandillon** [comment]
The error seems reanimated related, how can we reproduce the issue and how do you think there might be a bug on our side?

**Comment by Yaski** [comment]
I can try to create an isolated project with this crash.
There are some parts of the code that are shared with react-native-filament project. So I tried to use that library to check if it has the same error. 
They use quite different install instructions - I followed all of it:
https://margelo.github.io/react-native-filament/docs/guides

I don't have the crash when I render 3D with react-native-filament library. It means there is some specific problem with react-native-webgpu.

**Comment by Yaski** [comment]
@wcandillon I investigated the crash and found out that if I put HelloTriangle as main App screen (in index.js) then it renders and without crash. But when I put HelloTriangle inside Stack.Screen as component then the App crashes.

**Comment by wcandillon** [comment]
Is that something reproducible? In our example app for instance? or in another app?

**Comment by Yaski** [comment]
I will make example

**Comment by wcandillon** [comment]
@Yaski I think this should be fixed now :) :) but let me know if it is not.
