### ISSUE TITLE
Black canvas (and crash) after going from background to foreground on Android 

### ISSUE THREAD

**Issue by terrysahaidak** [wcandillon/react-native-webgpu#135]
After using webgpu canvas with skia i've noticed that when you switch to another app and then go back to your app where you have webgpu canvas showing - it will become blank.

I've confirmed this same problem in the example app, here is recording.

Pixel 8 pro running Android 14
webgpu 0.1.8

in our app we use RN 0.73

https://github.com/user-attachments/assets/fe0d9f85-5356-42b6-a043-d6077bda5723

**Comment by wcandillon** [comment]
#137 might fix it but we will double check
