### ISSUE TITLE
Black screen outside of canvas view

### ISSUE THREAD

**Issue by Yaski** [wcandillon/react-native-webgpu#139]
I want to embed webgl canvas inside of React Native Ui. But when I try to embed canvas in Ui everything outside the canvas becomes black. Any ideas how to fix this?
![Screenshot_20241009-024553](https://github.com/user-attachments/assets/82da2d6b-061d-438b-986b-d528b3b927dd)

**Comment by wcandillon** [comment]
indeed we currently use a surface view on Android but we will switch to a texture view very soon, probably this week.

**Comment by Yaski** [comment]
> indeed we currently use a surface view on Android but we will switch to a texture view very soon, probably this week.

Great! Thank you! Can I help you somehow?

**Comment by wcandillon** [comment]
in #137 you can simply swap the WebGPUView.java to use TextureView instead of surface view. We would gladly accept a PR for it. For simplicity it needs to be based on #137

**Comment by Yaski** [comment]
@wcandillon Ok, I will try to swap the Surface view. I will make a PR today or tomorrow.

**Comment by Yaski** [comment]
@wcandillon I made a PR but there is an issue that I mentioned in the PR
https://github.com/wcandillon/react-native-webgpu/pull/142
