### ISSUE TITLE
miss libwebgpu_dawn.so

### ISSUE THREAD

**Issue by MrQinYQ** [wcandillon/react-native-webgpu#159]
When I try to run the example project, I get a problem. error info:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-wgpu:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/qinyequan/Documents/GitHub/react-native-webgpu/node_modules/react-native-wgpu/android/.cxx/Debug/u6w6q4w2/arm64-v8a'
  
  C++ build system [build] failed while executing:
      /Users/qinyequan/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -C \
        /Users/qinyequan/Documents/GitHub/react-native-webgpu/node_modules/react-native-wgpu/android/.cxx/Debug/u6w6q4w2/arm64-v8a \
        react-native-wgpu
    from /Users/qinyequan/Documents/GitHub/react-native-webgpu/node_modules/react-native-wgpu/android
  ninja: error: '../../../../../libs/android/arm64-v8a/libwebgpu_dawn.so', needed by '../../../../build/intermediates/cxx/Debug/u6w6q4w2/obj/arm64-v8a/libreact-native-wgpu.so', missing and no known rule to make it
```
I updated react-native-wevgpu version.
![image](https://github.com/user-attachments/assets/58fd6f6f-c903-4a35-a86e-a8b1e20b8496)

I did not build this library because I do not have permission to download Dawn.
![image](https://github.com/user-attachments/assets/b15108d9-680d-43c9-a1c9-6baee9c7de1e)
I would like to know how to make the example project run locally. Thank you very much.

**Comment by wcandillon** [comment]
based on the screenshot it looks like you are try to run it from the example app, therefore you need to build dawn. And follow the following building steps:
https://github.com/wcandillon/react-native-webgpu?tab=readme-ov-file#building-dawn

I hope this helps. Let me know how it goes, if there is a bug there, we will reopen it.

**Comment by MrQinYQ** [comment]
🍏 arm64 xros -- Dawn: Configuring DawnGenerator for Dawn C++ wrapper.
🍏 arm64 xros -- Dawn: Configuring DawnGenerator for WebGPU headers.
🍏 arm64 xros -- Configuring done (39.8s)
🍏 arm64 xros CMake Error at src/tint/CMakeLists.txt:434 (add_library):
  Feature 'FRAMEWORK', specified through generator-expression
  '$<LINK_LIBRARY>' to link target 'tint_lang_msl_validate', is not supported
  for the 'CXX' link language.
Call Stack (most recent call first):
  src/tint/lang/msl/validate/BUILD.cmake:43 (tint_add_target)
  src/tint/lang/msl/BUILD.cmake:40 (include)
  src/tint/lang/BUILD.cmake:40 (include)
  src/tint/BUILD.cmake:39 (include)
  src/tint/CMakeLists.txt:690 (include)



🍏 arm64 xros -- Generating done (0.4s)
🍏 arm64 xros CMake Generate step failed.  Build files cannot be regenerated correctly.

/Users/qinyequan/Documents/GitHub/react-native-webgpu/packages/webgpu/scripts/build/util.ts:42
        reject(new Error(`${label} exited with code ${code}`));
               ^
Error: 🍏 arm64 xros exited with code 1
    at ChildProcess.<anonymous> (/Users/qinyequan/Documents/GitHub/react-native-webgpu/packages/webgpu/scripts/build/util.ts:42:16)
    at ChildProcess.emit (node:events:511:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by MrQinYQ** [comment]
I get the above error when I run "yarn build-dawn"

**Comment by wcandillon** [comment]
please have a look at these steps: https://github.com/wcandillon/react-native-webgpu?tab=readme-ov-file#building-dawn
You can excluse specific platforms and/or download the prebuilt binaries directly. They also are available here directly: https://github.com/wcandillon/react-native-webgpu/actions/runs/11372801632

**Comment by MrQinYQ** [comment]
The code downloaded from the main branch, running yarn build-dawn --exclude=xros,xrsimulator,macosx did not succeed because the build script did not filter out the platforms that were not built. I modified the build script and finally ran it through locally.
![image](https://github.com/user-attachments/assets/02aff2f9-a682-447d-9c4c-11cd15ce4331)
![image](https://github.com/user-attachments/assets/52ef2255-c9e3-40ac-9f86-40ef18024b33)

**Comment by MrQinYQ** [comment]
I am not proficient in C++, why does the xr device compilation fail on my machine? Is there anything I need to do?

**Comment by wcandillon** [comment]
please refer to this section: https://github.com/wcandillon/react-native-webgpu?tab=readme-ov-file#downloading-dawn then you won't need to compile anything. Hope we can get you up and running quickly
