### ISSUE TITLE
Three.js example no work in main branch now

### ISSUE THREAD

**Issue by MrQinYQ** [wcandillon/react-native-webgpu#185]
![image](https://github.com/user-attachments/assets/8903d5fa-815d-46b7-9a32-94e6dd8ca58f)
![image](https://github.com/user-attachments/assets/fb16b819-dbc4-4db9-8e2f-c7764053df61)
![image](https://github.com/user-attachments/assets/5683accb-38d3-4365-8c89-e3bcbae17b8d)
<img width="931" alt="image" src="https://github.com/user-attachments/assets/d5ae8017-56ed-4634-90d6-e5263a76a822">

**Comment by wcandillon** [comment]
This issue suggest that the module is not loaded correctly, I am closing it for now but if you have a small reproduction, I will reopen it immediately.

**Comment by MrQinYQ** [comment]
The current main branch can reproduce this problem. I see similar problems in the issue.
