### ISSUE TITLE
'webgpu/webgpu_cpp.h' file not found

### ISSUE THREAD

**Issue by chiragramimi** [wcandillon/react-native-webgpu#194]
![Screenshot 2024-12-18 at 2 15 35 PM](https://github.com/user-attachments/assets/dc23b19e-24df-41c1-b0bc-6c6334748efe)
![Screenshot 2024-12-18 at 2 17 18 PM](https://github.com/user-attachments/assets/26e8e82e-5c65-4b8c-b97c-86eddb65e698)

file not found when running in ios
@wcandillon

**Comment by wcandillon** [comment]
can you provide steps to reproduce the issue?

**Comment by chiragramimi** [comment]
> can you provide steps to reproduce the issue?

I have take a clone of the repo and run the apps/example

with steps:

1-> yarn install
2-> npx pod-install
3-> run from xcode in simulator.

I have also disable metal api.

@wcandillon

**Comment by wcandillon** [comment]
then you would need to follow these steps: https://github.com/wcandillon/react-native-webgpu?tab=readme-ov-file#library-development
