### ISSUE TITLE
iOS pod install : Unable to install vendored xcframework `libwebgpu_dawn`

### ISSUE THREAD

**Issue by Yaski** [wcandillon/react-native-webgpu#93]
Hello

I added react-native-webgpu to react native project with yarn add
Android build completed succesfully
But when I try to do pod install I get this error:

```
Installing react-native-wgpu (0.1.4)
Generating Pods project
[!] Unable to install vendored xcframework `libwebgpu_dawn` for Pod `react-native-wgpu` because it contains static libraries
with differing binary names: libwebgpu_dawn and libwebgpu_dawn_visionos.
```

**Comment by wcandillon** [comment]
my apologies for this regression, in the meantime you can safely use 0.1.3

**Comment by Yaski** [comment]
@wcandillon All is fine, thank you for fixing this 👍
